language: python
sudo: required

python:
  - "3.7"

install:
  - pip install pipenv
  - pip install codecov
  - pipenv install --dev

script:
  - pytest --tb=native --cov=./

after_success:
  - codecov
