trigger:
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'test-build-release'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- bash: |
    python -m pip install --upgrade pip
    pip install pipenv
  displayName: 'Install pipenv'

- bash: |
    pipenv install --dev
  displayName: 'Install dependencies using pipenv'

- bash: |
    pipenv run coverage run -m pytest
    ls
  displayName: Run pytest

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'
  env:
    CODECOV_TOKEN: $(slack_client_codecov_token)
