pr:
  branches:
    include:
    - 'master'

trigger:
  branches:
    include:
    - 'master'

name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'test-build-release'
- name: imageName
  value: '$(docker_id)/slack-client'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker login -u $(docker_id) -p $(docker_token)
  displayName: 'docker login'

- script: docker push $(imageName)
  displayName: 'docker push latest if this is the master branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
        docker tag $(imageName) $(imageName):$(build.buildNumber)
        docker push $(imageName):$(build.buildNumber)
  displayName: 'docker push with build number'
