apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
  namespace: slack-client
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret
  namespace: slack-client
  annotations:
    kubernetes.io/service-account.name: deploy-robot
type: kubernetes.io/service-account-token

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-master
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-robot-1
  namespace: slack-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-master
subjects:
- kind: ServiceAccount
  name: deploy-robot
  namespace: default


