apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret
  annotations:
    kubernetes.io/service-account.name: deploy-robot
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-robot-role
  namespace: default
rules: # ## Customize these to meet your requirements ##
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete","get"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-robot-role
  namespace: slack-client
rules: # ## Customize these to meet your requirements ##
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete","get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete","get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deploy-robot
  namespace: default
roleRef:
  kind: Role
  name: deploy-robot-role
  apiGroup: rbac.authorization.k8s.io
