apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-client
  namespace: slack-client
spec:
  selector:
      matchLabels:
        app: slack-client
  replicas: 1
  template:
      metadata:
        namespace: slack-client
        labels:
            app: slack-client
      spec:
        containers:
        - name: slack-client
<<<<<<< HEAD
          image: nkuik89/slack-client:5e8c70fba7d8922b1e70a49f92f6c27fa316839c
=======
          image: nkuik89/slack-client:f214322d4a30be41b19043596eae7a881bb29d9a
>>>>>>> 5e8c70fba7d8922b1e70a49f92f6c27fa316839c
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
          - containerPort: 8080
