apiVersion: v1
kind: Namespace
metadata:
  name: slack-client

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: slack-client-admin
  namespace: slack-client

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: slack-client-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: slack-client-admin
  namespace: slack-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-client
  namespace: slack-client
spec:
  selector:
      matchLabels:
        app: slack-client
  replicas: 1
  template:
      metadata:
        namespace: slack-client
        labels:
            app: slack-client
      spec:
        containers:
        - name: slack-client
          image: nkuik89/slack-client:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8000
              path: /healthz
          ports:
          - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: slack-client
  namespace: slack-client
spec:
  selector:
    app: slack-client
  ports:
    - port: 8000
