apiVersion: v1
kind: Service
metadata:
  name: slack-client
  namespace: slack-client
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocal: TCP
  type: LoadBalancer
  selector:
    app: slack-client
