{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slack-client.serviceAccountName" . }}
  namespace: {{ include "slack-client.fullname" . }}
  labels:
{{ include "slack-client.labels" . | nindent 4 }}
{{- end -}}
